name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
     - name: Check out respository code
       uses: actions/checkout@v3 # @v3 is the version of the checkout, if not defined it'll grab the latest and may cause issues when updated.
     - run: echo "$(cat hello_world.txt)"
